### ISSUE TITLE
Streamlit app not displaying within `policyengine-app` after pushing a change to this repo

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-api-demo#3]

**Comment by abhcs** [comment]
From [this link](https://blog.streamlit.io/host-your-streamlit-app-for-free/#step-5-deploy-your-app-in-a-few-clicks), if we had access to the streamlit account used to deploy the repo, then we could

> “Manage app” to see the log messages (use them for debugging and troubleshooting errors)

**Comment by anth-volk** [comment]
Yeah, unfortunately I don't have any connection with that. I'm sure Nikhil can advise on how to proceed.

**Comment by anth-volk** [comment]
This appears to be closed by app #[1237](https://github.com/PolicyEngine/policyengine-app/pull/1237).
